title: PingPong Benchamrk
email: phoenixilya@gmail.com
description: >-
  A benchmark for role-playing LLMs
baseurl: /ping_pong_bench/
url: https://ilyagusev.github.io/
github_username: IlyaGusev
markdown: kramdown
theme: jekyll-theme-minimal
